### ISSUE TITLE
Batch file doesn't work correctly.

### ISSUE THREAD

**Issue by BarisUygun** [it3xl/call_batch_from_wix_msi#1]
- Normally when i open the batch file it works correctly.
`@echo off
cmdkey.exe /list > "%TEMP%\List.txt"
findstr.exe Target "%TEMP%\List.txt" > "%TEMP%\tokensonly.txt"
FOR /F "tokens=1,2 delims= " %%G IN (%TEMP%\tokensonly.txt) DO cmdkey.exe /delete:%%H
del "%TEMP%\List.txt" /s /f /q
del "%TEMP%\tokensonly.txt" /s /f /q
echo All done
pause
`

- This is my batch file. It deletes windows credentials. How am i suppose to make it work in wix. I 
- execute the batch file according to your code but it gives a different output.
- This is the code i wrote.

` <File Id="FileDeleteCredentials" Name="deleteCredentials.bat" Source="deleteCredentials.bat" KeyPath="no" Vital="yes" />`

- 
`<CustomAction Id="RunDeployedBatchFile" Directory="INSTALLFOLDER" ExeCommand="[INSTALLFOLDER]deleteCredentials.bat" Execute="deferred" Impersonate="no" Return="ignore" />`

- 
`  <InstallExecuteSequence>
      <Custom Action="RunDeployedBatchFile" Before="RemoveFiles">
        <![CDATA[(NOT UPGRADINGPRODUCTCODE) AND (REMOVE~="ALL")]]>
      </Custom>
    </InstallExecuteSequence>`

**Comment by it3xl** [comment]
Hi, I need something to remember everything.
Could you strip out extra logic and give me your entire WiX project in an archive?
Or you can share your screen with me.

**Comment by BarisUygun** [comment]
- Hello, the problem was with
`<![CDATA[(NOT UPGRADINGPRODUCTCODE) AND (REMOVE~="ALL")]]>`
- this part when i got rid of it everything started working.

- Thank you for your time
