### ISSUE TITLE
Call batch silently

### ISSUE THREAD

**Issue by BarisUygun** [it3xl/call_batch_from_wix_msi#2]
- Hello, i am trying to execute my batch file silently without end user seeing it. The code that i have is this.

`<InstallExecuteSequence>
      <Custom Action="test"  Before="RemoveFiles"></Custom>
    </InstallExecuteSequence>`

- 

` <CustomAction Id="test"  ExeCommand="[INSTALLFOLDER]deleteCredentials.bat" Directory="INSTALLFOLDER"  Execute="deferred" Return="ignore"/>`

- How do i run deleteCredentials.bat silently?

**Comment by it3xl** [comment]
Hi, try to find something yourself
https://www.google.com/search?q=how+to+run+batch+file+without+a+window

**Comment by it3xl** [comment]
Also, consider to use PowerShell, or put all logic of your batch file into a .NET application.

**Comment by it3xl** [comment]
So, I'm happy if this was helpful.
Actually you've touched the famous trouble. Everybody are going through it time after time with Windows installers :)

**Comment by BarisUygun** [comment]
Hi thank you for your help. I couldn't find a way to do it with wix. But i turned the .bat file to an invisible .exe file so when i worked with it my problems was solved.

**Comment by it3xl** [comment]
Oh, interesting. Do you remember how you switched .exe to be invisible?

If you've used .NET for creating the .exe then it is better to use the lowest possible version of .NET.
For Windows compatibility reasons as, for example, Windows 7 (SP1) comes with the following . NET frameworks 1.0, 1.1, 2.0, 3.0 and 3.5.

**Comment by BarisUygun** [comment]
I just used a converter to make it invisible. Thank you for the information.

**Comment by it3xl** [comment]
A converter? Never heard about the converter.
You are welcome.
